Repository adobe/aem-project-archetype, pull requests merged in 2021-03, with the labels that each got.

#634 CQ-4315545 Enabling aem maven analyzer plugin for forms project
  src/main/resources/META-INF/archetype-post-generate.groovy
Labels: enhancement

#643 UI tests module improvements
  src/main/archetype/.gitignore
  src/main/archetype/ui.tests/.dockerignore
  src/main/archetype/ui.tests/test-module/package-lock.json
  src/main/archetype/ui.tests/test-module/package.json
  src/main/archetype/ui.tests/test-module/specs/aem/sites.js
  src/main/archetype/ui.tests/test-module/wdio.conf.commons.js
Labels: enhancement

#632 CIF-1921 - Minimal default styling for featured category list
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-cif/.content.xml
Labels: enhancement

#640 CIF-1922 - Minimal default styling for product teaser
  src/main/archetype/core/src/main/java/core/models/commerce/MyProductTeaser.java
  src/main/archetype/core/src/main/java/core/models/commerce/MyProductTeaserImpl.java
  src/main/archetype/core/src/main/java/core/models/commerce/package-info.java
  src/main/archetype/core/src/test/java/core/models/commerce/MyProductTeaserImplTest.java
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/productteaser/_cq_dialog/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/productteaser/productteaser.html
  src/main/archetype/ui.frontend.general/src/main/webpack/components/commerce/_productteaser.scss
Labels: bug

#644 Updating spa.project.core 1.2.0 to 1.2.8
  README.md
  src/main/archetype/pom.xml
Labels: enhancement

#650 CQ-4318408 Update core-forms-components version
  src/main/archetype/pom.xml
Labels: enhancement

#637 CIF-1920 - Move XFPage dialog extensions to CIF core components
  src/main/archetype/pom.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/_cq_dialog/.content.xml
  src/main/resources/META-INF/archetype-post-generate.groovy
Labels: to verify
